version: "3.9"

services:
  face-engine:
    build: .
    container_name: laravel_face_engine
    command: uvicorn app.engine_main:app --host 0.0.0.0 --port 9001 --workers 1
    volumes:
      - .:/app
      - insightface_cache:/root/.insightface
    working_dir: /app
    ports:
      - "9001:9001"
    environment:
      - APP_NAME=Laravel Face Engine
      - FACE_ENGINE_KEY=change-face-engine-key
      - ARCFACE_MODEL_NAME=buffalo_s
      - ARCFACE_DET_SIZE=320
      - ARCFACE_CTX_ID=-1
      - ARCFACE_ONNX_PROVIDERS=CPUExecutionProvider
      - OMP_NUM_THREADS=2
      - OPENBLAS_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - NUMEXPR_NUM_THREADS=2
      - INSIGHTFACE_HOME=/root/.insightface

volumes:
  insightface_cache:
